name: 2wp-app deploy UI for MainNet

on:
  push:
    tags:
      - '*-rc'

jobs:
  checkout-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name.
        id: get_tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.get_tag_name.outputs.VERSION }}

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: >
          VUE_APP_HOTJAR_ID=${{ secrets.MAINNET_VUE_APP_HOTJAR_ID }}
          VUE_APP_COIN='main'
          VUE_APP_MANIFEST_EMAIL='user@rsk.co'
          VUE_APP_MANIFEST_APP_URL='https://app.2wp.rootstock.io'
          VUE_APP_API_BASE_URL='https://api.2wp.rootstock.io'
          VUE_APP_RSK_NODE_HOST='https://public-node.rsk.co'
          VUE_APP_RSK_EXPLORER='https://explorer.rsk.co/'
          VUE_APP_WALLET_ADDRESSES_HARD_STOP=100
          VUE_APP_WALLET_ADDRESS_PER_CALL=5
          npm run-script build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.MAINNET_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.MAINNET_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy site to S3
        run: |
          aws s3 sync --delete --only-show-errors dist/ ${{ secrets.MAINNET_S3_BUCKET }}

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.MAINNET_CLOUDFRONT_DISTRIBUTION }} --paths "/*"
